name: Build RISC-V GNU Toolchain

on: workflow_dispatch

jobs:
  mac_os_12_x86:
    runs-on: macos-12
    steps:
      - name: Install deps
        run: |
          brew install python3 gawk gnu-sed gmp mpfr libmpc isl zlib expat
          brew tap discoteq/discoteq
          brew install flock

      - name: Build riscv-gnu-toolchain
        run: |
          git clone https://github.com/riscv/riscv-gnu-toolchain riscv-gnu-toolchain
          mkdir riscv
          cd riscv-gnu-toolchain
          git checkout 2022.09.21
          ./configure --prefix="$(dirname $(pwd))/riscv" --with-multilib-generator="rv32i-ilp32--;rv32iac-ilp32--;rv32im-ilp32--;rv32imc-ilp32--;rv32imf-ilp32--;rv32imf-ilp32f--;rv32imac-ilp32--;rv32imafc-ilp32f--;rv64imac-lp64--;rv64imafdc-lp64d--"
          make
          cd ..
          tar -czf riscv-gnu-toolchain-apple-x86.tar.gz riscv

      - name: Upload toolchain artifact
        uses: actions/upload-artifact@v3
        with:
          name: riscv-gnu-toolchain-apple-x86.tar.gz
          path: riscv-gnu-toolchain-apple-x86.tar.gz
