name: Build RISC-V GNU Toolchain Linux

on: workflow_dispatch

jobs:
  mac_os_12_x86:
    runs-on: ubuntu-22.04
    steps:
      - name: Install deps
        run: |
          apt-get install -y autoconf automake autotools-dev curl python3 libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex texinfo gperf libtool patchutils bc zlib1g-dev libexpat-dev

      - name: Build riscv-gnu-toolchain
        run: |
          git clone https://github.com/riscv/riscv-gnu-toolchain riscv-gnu-toolchain
          mkdir riscv
          cd riscv-gnu-toolchain
          ./configure --prefix="$(dirname $(pwd))/riscv" --enable-multilib
          make
          cd ..
          tar -czf riscv-gnu-toolchain-ubuntu-22.04.tar.gz riscv

      - name: Upload toolchain artifact
        uses: actions/upload-artifact@v3
        with:
          name: riscv-gnu-toolchain-ubuntu-22.04.tar.gz
          path: riscv-gnu-toolchain-ubuntu-22.04.tar.gz
